# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app-gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 730)
        MainWindow.setMinimumSize(QtCore.QSize(480, 700))
        MainWindow.setMaximumSize(QtCore.QSize(480, 750))
        MainWindow.setStyleSheet("/*background-color: rgb(17, 25, 39);*/\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("background-color: #111927;\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.topLogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.topLogoLabel.setStyleSheet("\n"
"padding: 10;\n"
"")
        self.topLogoLabel.setText("")
        self.topLogoLabel.setPixmap(QtGui.QPixmap(":/icons/app-logo-small.png"))
        self.topLogoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.topLogoLabel.setObjectName("topLogoLabel")
        self.verticalLayout_8.addWidget(self.topLogoLabel)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("QWidget {\n"
"border-radius: 15;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"color: #93dd03;\n"
"background-color: #111927;\n"
"border-radius: 15;\n"
"border: 1px solid;\n"
"border-color: #93dd03;\n"
"font-size: 15pt;\n"
"margin: 15;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #93dd03;\n"
"color: #111927;\n"
"}\n"
"\n"
"QLabel {\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.connectProxmarkPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectProxmarkPage.sizePolicy().hasHeightForWidth())
        self.connectProxmarkPage.setSizePolicy(sizePolicy)
        self.connectProxmarkPage.setObjectName("connectProxmarkPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.connectProxmarkPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connectionPageContainer = QtWidgets.QWidget(self.connectProxmarkPage)
        self.connectionPageContainer.setObjectName("connectionPageContainer")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.connectionPageContainer)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pxmkappLabel = QtWidgets.QLabel(self.connectionPageContainer)
        self.pxmkappLabel.setMinimumSize(QtCore.QSize(0, 60))
        self.pxmkappLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pxmkappLabel.setFont(font)
        self.pxmkappLabel.setStyleSheet("\n"
"\n"
"")
        self.pxmkappLabel.setText("")
        self.pxmkappLabel.setPixmap(QtGui.QPixmap(":/icons/app-logo.png"))
        self.pxmkappLabel.setScaledContents(False)
        self.pxmkappLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pxmkappLabel.setObjectName("pxmkappLabel")
        self.verticalLayout_9.addWidget(self.pxmkappLabel)
        self.connectProxmarkButton = QtWidgets.QPushButton(self.connectionPageContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectProxmarkButton.sizePolicy().hasHeightForWidth())
        self.connectProxmarkButton.setSizePolicy(sizePolicy)
        self.connectProxmarkButton.setMinimumSize(QtCore.QSize(350, 150))
        self.connectProxmarkButton.setMaximumSize(QtCore.QSize(600, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.connectProxmarkButton.setFont(font)
        self.connectProxmarkButton.setAutoFillBackground(False)
        self.connectProxmarkButton.setStyleSheet("")
        self.connectProxmarkButton.setObjectName("connectProxmarkButton")
        self.verticalLayout_9.addWidget(self.connectProxmarkButton)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem)
        self.verticalLayout.addWidget(self.connectionPageContainer, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.connectProxmarkPage)
        self.mifarePage = QtWidgets.QWidget()
        self.mifarePage.setObjectName("mifarePage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.mifarePage)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.mifareStackedWidget = QtWidgets.QStackedWidget(self.mifarePage)
        self.mifareStackedWidget.setStyleSheet("QStackedWidget {\n"
"border-radius: 10;\n"
"background-color: #1a2332;\n"
"}")
        self.mifareStackedWidget.setObjectName("mifareStackedWidget")
        self.mifareOptionsPage = QtWidgets.QWidget()
        self.mifareOptionsPage.setObjectName("mifareOptionsPage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.mifareOptionsPage)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.mifareOptionsContainer = QtWidgets.QWidget(self.mifareOptionsPage)
        self.mifareOptionsContainer.setAutoFillBackground(False)
        self.mifareOptionsContainer.setStyleSheet("QWidget#mifareOptionsContainer {\n"
"\n"
"\n"
"background-color: #1a2332;\n"
"}")
        self.mifareOptionsContainer.setObjectName("mifareOptionsContainer")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.mifareOptionsContainer)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.readMifareTagButton = QtWidgets.QPushButton(self.mifareOptionsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readMifareTagButton.sizePolicy().hasHeightForWidth())
        self.readMifareTagButton.setSizePolicy(sizePolicy)
        self.readMifareTagButton.setMinimumSize(QtCore.QSize(0, 120))
        self.readMifareTagButton.setAutoFillBackground(False)
        self.readMifareTagButton.setObjectName("readMifareTagButton")
        self.verticalLayout_20.addWidget(self.readMifareTagButton)
        self.cloneMifareTagButton = QtWidgets.QPushButton(self.mifareOptionsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cloneMifareTagButton.sizePolicy().hasHeightForWidth())
        self.cloneMifareTagButton.setSizePolicy(sizePolicy)
        self.cloneMifareTagButton.setMinimumSize(QtCore.QSize(0, 120))
        self.cloneMifareTagButton.setObjectName("cloneMifareTagButton")
        self.verticalLayout_20.addWidget(self.cloneMifareTagButton)
        self.simulateMifareTagButton = QtWidgets.QPushButton(self.mifareOptionsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateMifareTagButton.sizePolicy().hasHeightForWidth())
        self.simulateMifareTagButton.setSizePolicy(sizePolicy)
        self.simulateMifareTagButton.setMinimumSize(QtCore.QSize(0, 120))
        self.simulateMifareTagButton.setObjectName("simulateMifareTagButton")
        self.verticalLayout_20.addWidget(self.simulateMifareTagButton)
        self.verticalLayout_12.addWidget(self.mifareOptionsContainer)
        self.mifareStackedWidget.addWidget(self.mifareOptionsPage)
        self.mifareResultsPage = QtWidgets.QWidget()
        self.mifareResultsPage.setObjectName("mifareResultsPage")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.mifareResultsPage)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.mifareTagInformationLabel = QtWidgets.QLabel(self.mifareResultsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mifareTagInformationLabel.sizePolicy().hasHeightForWidth())
        self.mifareTagInformationLabel.setSizePolicy(sizePolicy)
        self.mifareTagInformationLabel.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.mifareTagInformationLabel.setFont(font)
        self.mifareTagInformationLabel.setStyleSheet("color: rgb(33, 136, 145);")
        self.mifareTagInformationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mifareTagInformationLabel.setObjectName("mifareTagInformationLabel")
        self.verticalLayout_14.addWidget(self.mifareTagInformationLabel)
        self.mifareTagResultsLabel = QtWidgets.QLabel(self.mifareResultsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mifareTagResultsLabel.sizePolicy().hasHeightForWidth())
        self.mifareTagResultsLabel.setSizePolicy(sizePolicy)
        self.mifareTagResultsLabel.setMinimumSize(QtCore.QSize(0, 230))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.mifareTagResultsLabel.setFont(font)
        self.mifareTagResultsLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10;\n"
"padding: 10px;\n"
"border: 10px;")
        self.mifareTagResultsLabel.setText("")
        self.mifareTagResultsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mifareTagResultsLabel.setObjectName("mifareTagResultsLabel")
        self.verticalLayout_14.addWidget(self.mifareTagResultsLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cloneMifareButton = QtWidgets.QPushButton(self.mifareResultsPage)
        self.cloneMifareButton.setMinimumSize(QtCore.QSize(120, 80))
        self.cloneMifareButton.setObjectName("cloneMifareButton")
        self.horizontalLayout_2.addWidget(self.cloneMifareButton)
        self.viewMemoryMifareButton = QtWidgets.QPushButton(self.mifareResultsPage)
        self.viewMemoryMifareButton.setMinimumSize(QtCore.QSize(120, 80))
        self.viewMemoryMifareButton.setObjectName("viewMemoryMifareButton")
        self.horizontalLayout_2.addWidget(self.viewMemoryMifareButton)
        self.simulateMifareButton = QtWidgets.QPushButton(self.mifareResultsPage)
        self.simulateMifareButton.setMinimumSize(QtCore.QSize(120, 80))
        self.simulateMifareButton.setObjectName("simulateMifareButton")
        self.horizontalLayout_2.addWidget(self.simulateMifareButton)
        self.verticalLayout_14.addLayout(self.horizontalLayout_2)
        self.mifareStackedWidget.addWidget(self.mifareResultsPage)
        self.mifareCloneResultsPage = QtWidgets.QWidget()
        self.mifareCloneResultsPage.setObjectName("mifareCloneResultsPage")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.mifareCloneResultsPage)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.mifareCloneResultsLabel = QtWidgets.QLabel(self.mifareCloneResultsPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mifareCloneResultsLabel.setFont(font)
        self.mifareCloneResultsLabel.setStyleSheet("color: rgb(255, 255, 255)")
        self.mifareCloneResultsLabel.setText("")
        self.mifareCloneResultsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mifareCloneResultsLabel.setObjectName("mifareCloneResultsLabel")
        self.verticalLayout_19.addWidget(self.mifareCloneResultsLabel)
        self.mifareCloneResultsOkButton = QtWidgets.QPushButton(self.mifareCloneResultsPage)
        self.mifareCloneResultsOkButton.setMinimumSize(QtCore.QSize(0, 80))
        self.mifareCloneResultsOkButton.setObjectName("mifareCloneResultsOkButton")
        self.verticalLayout_19.addWidget(self.mifareCloneResultsOkButton)
        self.mifareStackedWidget.addWidget(self.mifareCloneResultsPage)
        self.mifareClonePage = QtWidgets.QWidget()
        self.mifareClonePage.setObjectName("mifareClonePage")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.mifareClonePage)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.mifareStackedWidget.addWidget(self.mifareClonePage)
        self.memoryLayoutPage = QtWidgets.QWidget()
        self.memoryLayoutPage.setObjectName("memoryLayoutPage")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.memoryLayoutPage)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tagMemoryLabel = QtWidgets.QLabel(self.memoryLayoutPage)
        self.tagMemoryLabel.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.tagMemoryLabel.setFont(font)
        self.tagMemoryLabel.setStyleSheet("color: rgb(33, 136, 145);")
        self.tagMemoryLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tagMemoryLabel.setObjectName("tagMemoryLabel")
        self.verticalLayout_15.addWidget(self.tagMemoryLabel)
        self.scrollArea = QtWidgets.QScrollArea(self.memoryLayoutPage)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"    width: 30px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 390, 323))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.memoryLayoutLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        self.memoryLayoutLabel.setFont(font)
        self.memoryLayoutLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.memoryLayoutLabel.setText("")
        self.memoryLayoutLabel.setObjectName("memoryLayoutLabel")
        self.verticalLayout_18.addWidget(self.memoryLayoutLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_15.addWidget(self.scrollArea)
        self.memoryOkButton = QtWidgets.QPushButton(self.memoryLayoutPage)
        self.memoryOkButton.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.memoryOkButton.setFont(font)
        self.memoryOkButton.setObjectName("memoryOkButton")
        self.verticalLayout_15.addWidget(self.memoryOkButton)
        self.mifareStackedWidget.addWidget(self.memoryLayoutPage)
        self.verticalLayout_11.addWidget(self.mifareStackedWidget, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.mifarePage)
        self.resultsPage = QtWidgets.QWidget()
        self.resultsPage.setObjectName("resultsPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.resultsPage)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.resultsPageContainer = QtWidgets.QWidget(self.resultsPage)
        self.resultsPageContainer.setStyleSheet("QWidget#resultsPageContainer {\n"
"background-color: #1a2332;\n"
"border-radius: 10;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"margin: 30px 0 30px 0;\n"
"width: 35px;\n"
"border-right: 1px solid #93dd03;\n"
"border-left: 1px solid #93dd03;\n"
"background-color: #263143;\n"
"border-radius: 0;\n"
"}\n"
"\n"
"QScrollBar::handle::vertical {\n"
"border: 1px solid #93dd03;\n"
"background-color: #111927;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"border: 1px solid #93dd03;\n"
"height: 30px;\n"
"border-top-left-radius: 7px;\n"
"border-top-right-radius: 7px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"background-color: #111927;\n"
"color: #93dd03;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"border: 1px solid #93dd03;\n"
"height: 30px;\n"
"border-bottom-left-radius: 7px;\n"
"border-bottom-right-radius: 7px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"background-color: #111927;\n"
"color: #93dd03;\n"
"}")
        self.resultsPageContainer.setObjectName("resultsPageContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.resultsPageContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.resultsPageTitleLabel = QtWidgets.QLabel(self.resultsPageContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsPageTitleLabel.sizePolicy().hasHeightForWidth())
        self.resultsPageTitleLabel.setSizePolicy(sizePolicy)
        self.resultsPageTitleLabel.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.resultsPageTitleLabel.setFont(font)
        self.resultsPageTitleLabel.setStyleSheet("color: #93dd03;\n"
"background-color: #111927;\n"
"border-radius: 15;\n"
"margin: 5px;\n"
"margin-left: 40px;\n"
"margin-right: 40px;")
        self.resultsPageTitleLabel.setText("")
        self.resultsPageTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultsPageTitleLabel.setObjectName("resultsPageTitleLabel")
        self.verticalLayout_2.addWidget(self.resultsPageTitleLabel)
        self.resultsPageScrollArea = QtWidgets.QScrollArea(self.resultsPageContainer)
        self.resultsPageScrollArea.setMinimumSize(QtCore.QSize(400, 0))
        self.resultsPageScrollArea.setStyleSheet("")
        self.resultsPageScrollArea.setWidgetResizable(True)
        self.resultsPageScrollArea.setObjectName("resultsPageScrollArea")
        self.resultsPageScrollAreaWidgetContents = QtWidgets.QWidget()
        self.resultsPageScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 400, 417))
        self.resultsPageScrollAreaWidgetContents.setObjectName("resultsPageScrollAreaWidgetContents")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.resultsPageScrollAreaWidgetContents)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.resultsPageDataLabel = QtWidgets.QLabel(self.resultsPageScrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsPageDataLabel.sizePolicy().hasHeightForWidth())
        self.resultsPageDataLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(13)
        self.resultsPageDataLabel.setFont(font)
        self.resultsPageDataLabel.setStyleSheet("")
        self.resultsPageDataLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.resultsPageDataLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.resultsPageDataLabel.setText("")
        self.resultsPageDataLabel.setScaledContents(False)
        self.resultsPageDataLabel.setWordWrap(False)
        self.resultsPageDataLabel.setObjectName("resultsPageDataLabel")
        self.verticalLayout_21.addWidget(self.resultsPageDataLabel)
        self.resultsPageScrollArea.setWidget(self.resultsPageScrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.resultsPageScrollArea)
        self.verticalLayout_10.addWidget(self.resultsPageContainer, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.resultsPage)
        self.mainMenuPage = QtWidgets.QWidget()
        self.mainMenuPage.setStyleSheet("QWidget#mainMenuPage {\n"
"margin: 0;\n"
"padding: 0px;\n"
"}")
        self.mainMenuPage.setObjectName("mainMenuPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mainMenuPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mainMenuContainer = QtWidgets.QWidget(self.mainMenuPage)
        self.mainMenuContainer.setStyleSheet("QWidget#mainMenuContainer {\n"
"padding: 20px;\n"
"background-color: #1a2332;\n"
"border-radius: 15;\n"
"}")
        self.mainMenuContainer.setObjectName("mainMenuContainer")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.mainMenuContainer)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.basicCommandsButton = QtWidgets.QPushButton(self.mainMenuContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basicCommandsButton.sizePolicy().hasHeightForWidth())
        self.basicCommandsButton.setSizePolicy(sizePolicy)
        self.basicCommandsButton.setMinimumSize(QtCore.QSize(200, 120))
        self.basicCommandsButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.basicCommandsButton.setFont(font)
        self.basicCommandsButton.setStyleSheet("")
        self.basicCommandsButton.setObjectName("basicCommandsButton")
        self.verticalLayout_23.addWidget(self.basicCommandsButton)
        self.mifare1kButton = QtWidgets.QPushButton(self.mainMenuContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mifare1kButton.sizePolicy().hasHeightForWidth())
        self.mifare1kButton.setSizePolicy(sizePolicy)
        self.mifare1kButton.setMinimumSize(QtCore.QSize(200, 120))
        self.mifare1kButton.setMaximumSize(QtCore.QSize(1777777, 1777777))
        self.mifare1kButton.setObjectName("mifare1kButton")
        self.verticalLayout_23.addWidget(self.mifare1kButton)
        self.customCommandButton = QtWidgets.QPushButton(self.mainMenuContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customCommandButton.sizePolicy().hasHeightForWidth())
        self.customCommandButton.setSizePolicy(sizePolicy)
        self.customCommandButton.setMinimumSize(QtCore.QSize(200, 120))
        self.customCommandButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.customCommandButton.setObjectName("customCommandButton")
        self.verticalLayout_23.addWidget(self.customCommandButton)
        self.savedTagsButton = QtWidgets.QPushButton(self.mainMenuContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savedTagsButton.sizePolicy().hasHeightForWidth())
        self.savedTagsButton.setSizePolicy(sizePolicy)
        self.savedTagsButton.setMinimumSize(QtCore.QSize(200, 120))
        self.savedTagsButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.savedTagsButton.setObjectName("savedTagsButton")
        self.verticalLayout_23.addWidget(self.savedTagsButton)
        self.verticalLayout_5.addWidget(self.mainMenuContainer)
        self.stackedWidget.addWidget(self.mainMenuPage)
        self.connectingMessagePage = QtWidgets.QWidget()
        self.connectingMessagePage.setObjectName("connectingMessagePage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.connectingMessagePage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.connectionStatusLabel = QtWidgets.QLabel(self.connectingMessagePage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.connectionStatusLabel.setFont(font)
        self.connectionStatusLabel.setText("")
        self.connectionStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.connectionStatusLabel.setObjectName("connectionStatusLabel")
        self.verticalLayout_6.addWidget(self.connectionStatusLabel)
        self.connectionOkButton = QtWidgets.QPushButton(self.connectingMessagePage)
        self.connectionOkButton.setEnabled(True)
        self.connectionOkButton.setMinimumSize(QtCore.QSize(0, 80))
        self.connectionOkButton.setObjectName("connectionOkButton")
        self.verticalLayout_6.addWidget(self.connectionOkButton)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.stackedWidget.addWidget(self.connectingMessagePage)
        self.basicCommandsPage = QtWidgets.QWidget()
        self.basicCommandsPage.setStyleSheet("")
        self.basicCommandsPage.setObjectName("basicCommandsPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.basicCommandsPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.basicCommandsContainer = QtWidgets.QWidget(self.basicCommandsPage)
        self.basicCommandsContainer.setStyleSheet("QWidget#basicCommandsContainer {\n"
"padding: 20px;\n"
"background-color: #1a2332;\n"
"border-radius: 15;\n"
"}")
        self.basicCommandsContainer.setObjectName("basicCommandsContainer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.basicCommandsContainer)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hwStatusButton = QtWidgets.QPushButton(self.basicCommandsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hwStatusButton.sizePolicy().hasHeightForWidth())
        self.hwStatusButton.setSizePolicy(sizePolicy)
        self.hwStatusButton.setMinimumSize(QtCore.QSize(0, 120))
        self.hwStatusButton.setObjectName("hwStatusButton")
        self.verticalLayout_4.addWidget(self.hwStatusButton)
        self.autoDetectTagButton = QtWidgets.QPushButton(self.basicCommandsContainer)
        self.autoDetectTagButton.setMinimumSize(QtCore.QSize(0, 120))
        self.autoDetectTagButton.setObjectName("autoDetectTagButton")
        self.verticalLayout_4.addWidget(self.autoDetectTagButton)
        self.readLFTagButton = QtWidgets.QPushButton(self.basicCommandsContainer)
        self.readLFTagButton.setMinimumSize(QtCore.QSize(0, 120))
        self.readLFTagButton.setObjectName("readLFTagButton")
        self.verticalLayout_4.addWidget(self.readLFTagButton)
        self.readHFTagButton = QtWidgets.QPushButton(self.basicCommandsContainer)
        self.readHFTagButton.setMinimumSize(QtCore.QSize(0, 120))
        self.readHFTagButton.setObjectName("readHFTagButton")
        self.verticalLayout_4.addWidget(self.readHFTagButton)
        self.verticalLayout_3.addWidget(self.basicCommandsContainer)
        self.stackedWidget.addWidget(self.basicCommandsPage)
        self.verticalLayout_8.addWidget(self.stackedWidget)
        self.verticalLayout_13.addLayout(self.verticalLayout_8)
        self.backExitContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backExitContainer.sizePolicy().hasHeightForWidth())
        self.backExitContainer.setSizePolicy(sizePolicy)
        self.backExitContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.backExitContainer.setStyleSheet("QWidget#backExitContainer {\n"
"/*background-color: #1a2332;*/\n"
"padding: 0px;\n"
"margin: 0;\n"
"border-radius: 15;\n"
"}\n"
"QPushButton {\n"
"border-radius: 15;\n"
"background-color: #111927;\n"
"}")
        self.backExitContainer.setObjectName("backExitContainer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.backExitContainer)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.backButton = QtWidgets.QPushButton(self.backExitContainer)
        self.backButton.setMinimumSize(QtCore.QSize(100, 60))
        self.backButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("QPushButton {\n"
"color: #93dd03;\n"
"border: 1px solid;\n"
"border-color: #93dd03;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #93dd03;\n"
"color: #111927;\n"
"}\n"
"")
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_3.addWidget(self.backButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.exitButton = QtWidgets.QPushButton(self.backExitContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setMinimumSize(QtCore.QSize(100, 60))
        self.exitButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("QPushButton {\n"
"color: #c43437;\n"
"border: 1px solid;\n"
"border-color: #c43437;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #c43437;\n"
"color: #111927;\n"
"}")
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_3.addWidget(self.exitButton)
        self.verticalLayout_13.addWidget(self.backExitContainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.mifareStackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectProxmarkButton.setText(_translate("MainWindow", "CONNECT PROXMARK"))
        self.readMifareTagButton.setText(_translate("MainWindow", "READ TAG"))
        self.cloneMifareTagButton.setText(_translate("MainWindow", "CLONE TAG"))
        self.simulateMifareTagButton.setText(_translate("MainWindow", "SIMULATE TAG"))
        self.mifareTagInformationLabel.setText(_translate("MainWindow", "TAG INFORMATION"))
        self.cloneMifareButton.setText(_translate("MainWindow", "CLONE"))
        self.viewMemoryMifareButton.setText(_translate("MainWindow", "VIEW\n"
"MEMORY"))
        self.simulateMifareButton.setText(_translate("MainWindow", "SIMULATE"))
        self.mifareCloneResultsOkButton.setText(_translate("MainWindow", "OK"))
        self.tagMemoryLabel.setText(_translate("MainWindow", "TAG MEMORY"))
        self.memoryOkButton.setText(_translate("MainWindow", "OK"))
        self.basicCommandsButton.setText(_translate("MainWindow", "BASIC COMMANDS"))
        self.mifare1kButton.setText(_translate("MainWindow", "MIFARE 1K"))
        self.customCommandButton.setText(_translate("MainWindow", "CUSTOM\n"
"COMMAND"))
        self.savedTagsButton.setText(_translate("MainWindow", "SAVED\n"
"TAGS"))
        self.connectionOkButton.setText(_translate("MainWindow", "OK"))
        self.hwStatusButton.setText(_translate("MainWindow", "HARDWARE STATUS"))
        self.autoDetectTagButton.setText(_translate("MainWindow", "AUTO-DETECT TAG"))
        self.readLFTagButton.setText(_translate("MainWindow", "READ LOW-FREQUENCY TAG"))
        self.readHFTagButton.setText(_translate("MainWindow", "READ HIGH-FREQUENCY TAG"))
        self.backButton.setText(_translate("MainWindow", "BACK"))
        self.exitButton.setText(_translate("MainWindow", "EXIT"))
import resources_rc
